/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.AlumnoData;
import Controlador.InscripcionData;
import Controlador.MateriaData;
import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class AlumnosMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlumnosMateriasView
     */
    
    private DefaultTableModel modelo;
    private ArrayList<Inscripcion> listaInscripciones;
    private ArrayList<Materia> listaMaterias;
    private ArrayList<Alumno> listaAlumnos;
    private InscripcionData inscData;
    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private Conexion conexion;
    
    public AlumnosMaterias() {
        initComponents();
        inscData = new InscripcionData();
        modelo = new DefaultTableModel();
        listaInscripciones = (ArrayList)inscData.buscarTodasInscripciones();
        
        materiaData = new MateriaData();
        listaMaterias = (ArrayList)materiaData.listarMaterias();
        
        alumnoData = new AlumnoData();
        listaAlumnos = (ArrayList<Alumno>)alumnoData.listarAlumnos();
        
        cargarMaterias();
        armaCabeceraTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAxMTitulo = new javax.swing.JLabel();
        lblAxMMateria = new javax.swing.JLabel();
        cmbAxMMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        aXmTablaAlumnos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblAxMTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAxMTitulo.setText("Listado de alumnos por Materia");

        lblAxMMateria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblAxMMateria.setText("Materia: ");

        cmbAxMMaterias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbAxMMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAxMMateriasActionPerformed(evt);
            }
        });

        aXmTablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(aXmTablaAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblAxMTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblAxMMateria)
                        .addGap(44, 44, 44)
                        .addComponent(cmbAxMMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAxMTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAxMMateria)
                    .addComponent(cmbAxMMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAxMMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAxMMateriasActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_cmbAxMMateriasActionPerformed
    
    public void cargarMaterias(){
        for (Materia item: listaMaterias) {
            cmbAxMMaterias.addItem(item);
        }
    }

    public void armaCabeceraTabla(){
        ArrayList<Object> columns = new ArrayList<Object>();
        columns.add("ID");
        columns.add("Apellido");
        columns.add("Nombre");
        columns.add("Nota");
        for(Object it: columns){
            modelo.addColumn(it);
        }
        aXmTablaAlumnos.setModel(modelo); 
    }
    
    public void borrarFilasTabla(){
        int a = modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    public void cargarDatos(){
        borrarFilasTabla();
        
        Materia mat = (Materia)cmbAxMMaterias.getSelectedItem();
        for(Inscripcion insc: listaInscripciones){
            if(insc.getMateria().getIdMateria()==mat.getIdMateria()){
                modelo.addRow(new Object[]{insc.getAlumno().getIdAlumno(), insc.getAlumno().getApellido(), insc.getAlumno().getNombre(), insc.getNota()} );
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aXmTablaAlumnos;
    private javax.swing.JComboBox<Materia> cmbAxMMaterias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAxMMateria;
    private javax.swing.JLabel lblAxMTitulo;
    // End of variables declaration//GEN-END:variables
}
