/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.MateriaData;
import Modelo.Materia;

/**
 *
 * @author carlo
 */
public class FormMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormMateria
     */
    private MateriaData materiaData;
    
    
    public FormMateria() {
        initComponents();
        materiaData = new MateriaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMateriaTitulo = new javax.swing.JLabel();
        lblMateriaId = new javax.swing.JLabel();
        lblMateriaAnio = new javax.swing.JLabel();
        lblMateriaNombre = new javax.swing.JLabel();
        txtMateriaId = new javax.swing.JTextField();
        txtMateriaAnio = new javax.swing.JTextField();
        txtMateriaNombre = new javax.swing.JTextField();
        btnMateriaGuardar = new javax.swing.JButton();
        btnMateriaBorrar = new javax.swing.JButton();
        btnMateriaActualizar = new javax.swing.JButton();
        btnMateriaLimpiar = new javax.swing.JButton();
        btnMateriaBuscar = new javax.swing.JButton();
        btnMateriaActivar = new javax.swing.JButton();
        lblMateriaActivo = new javax.swing.JLabel();
        lblMateriaEstado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(600, 400));

        lblMateriaTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMateriaTitulo.setText("Materias");

        lblMateriaId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMateriaId.setText("Id Materia:");

        lblMateriaAnio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMateriaAnio.setText("Año:");

        lblMateriaNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMateriaNombre.setText("Nombre:");

        txtMateriaId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtMateriaAnio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtMateriaNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnMateriaGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMateriaGuardar.setText("Guardar");
        btnMateriaGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaGuardarActionPerformed(evt);
            }
        });

        btnMateriaBorrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMateriaBorrar.setText("Borrar");
        btnMateriaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaBorrarActionPerformed(evt);
            }
        });

        btnMateriaActualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMateriaActualizar.setText("Actualizar");
        btnMateriaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActualizarActionPerformed(evt);
            }
        });

        btnMateriaLimpiar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMateriaLimpiar.setText("Limpiar");
        btnMateriaLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaLimpiarActionPerformed(evt);
            }
        });

        btnMateriaBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMateriaBuscar.setText("Buscar");
        btnMateriaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaBuscarActionPerformed(evt);
            }
        });

        btnMateriaActivar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMateriaActivar.setText("Activar");
        btnMateriaActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActivarActionPerformed(evt);
            }
        });

        lblMateriaActivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMateriaActivo.setText("Estado:");

        lblMateriaEstado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMateriaActualizar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(lblMateriaTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMateriaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnMateriaBorrar)
                                .addGap(30, 30, 30)
                                .addComponent(btnMateriaActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnMateriaLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMateriaId)
                                    .addComponent(lblMateriaAnio)
                                    .addComponent(lblMateriaNombre))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMateriaId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMateriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMateriaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(lblMateriaActivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMateriaEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtMateriaNombre))))))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMateriaTitulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateriaId)
                    .addComponent(txtMateriaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMateriaBuscar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateriaAnio)
                    .addComponent(txtMateriaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMateriaActivo)
                    .addComponent(lblMateriaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateriaNombre)
                    .addComponent(txtMateriaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMateriaActualizar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMateriaGuardar)
                    .addComponent(btnMateriaBorrar)
                    .addComponent(btnMateriaLimpiar)
                    .addComponent(btnMateriaActivar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMateriaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaGuardarActionPerformed
        // TODO add your handling code here:
        int anio = Integer.parseInt(txtMateriaAnio.getText());
        String nombre = txtMateriaNombre.getText();
        boolean estado = true;
        Materia materia = new Materia(nombre, anio, estado);
        materiaData.guardarMateria(materia);
        txtMateriaId.setText(materia.getIdMateria()+"");
        lblMateriaEstado.setText("Activa");
    }//GEN-LAST:event_btnMateriaGuardarActionPerformed

    private void btnMateriaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaBorrarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtMateriaId.getText());
        materiaData.eliminarMateria(id);
        lblMateriaEstado.setText("Inactiva");
    }//GEN-LAST:event_btnMateriaBorrarActionPerformed

    private void btnMateriaActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActivarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtMateriaId.getText());
        materiaData.activarMateria(id);
        lblMateriaEstado.setText("Activa");        
    }//GEN-LAST:event_btnMateriaActivarActionPerformed

    private void btnMateriaLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaLimpiarActionPerformed
        // TODO add your handling code here:
        txtMateriaId.setText("");
        txtMateriaAnio.setText("");
        txtMateriaNombre.setText("");
        lblMateriaEstado.setText("");
    }//GEN-LAST:event_btnMateriaLimpiarActionPerformed

    private void btnMateriaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaBuscarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtMateriaId.getText());
        Materia materia = materiaData.buscarMateria(id);
        if(materia!=null){
            txtMateriaId.setText(materia.getIdMateria()+"");
            txtMateriaAnio.setText(materia.getAnio()+"");
            txtMateriaNombre.setText(materia.getNombre());
            if (materia.isEstado()==true){
                lblMateriaEstado.setText("Activa");
            }else if (materia.isEstado()==false){
                lblMateriaEstado.setText("Inactiva");
            }
        }
        
    }//GEN-LAST:event_btnMateriaBuscarActionPerformed

    private void btnMateriaActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActualizarActionPerformed
        // TODO add your handling code here:
        if(txtMateriaId.getText()!=null){
            int id = Integer.parseInt(txtMateriaId.getText());
            int anio = Integer.parseInt(txtMateriaAnio.getText());
            String nombre = txtMateriaNombre.getText();
            String activo = lblMateriaEstado.getText();
            boolean estado;            
            if ("Activo".equals(activo)){
                estado = true;
            }else{
                estado = false;
            }
            Materia materia = new Materia(id, nombre, anio, estado);
            materiaData.modificarMateria(materia);
        }        
    }//GEN-LAST:event_btnMateriaActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMateriaActivar;
    private javax.swing.JButton btnMateriaActualizar;
    private javax.swing.JButton btnMateriaBorrar;
    private javax.swing.JButton btnMateriaBuscar;
    private javax.swing.JButton btnMateriaGuardar;
    private javax.swing.JButton btnMateriaLimpiar;
    private javax.swing.JLabel lblMateriaActivo;
    private javax.swing.JLabel lblMateriaAnio;
    private javax.swing.JLabel lblMateriaEstado;
    private javax.swing.JLabel lblMateriaId;
    private javax.swing.JLabel lblMateriaNombre;
    private javax.swing.JLabel lblMateriaTitulo;
    private javax.swing.JTextField txtMateriaAnio;
    private javax.swing.JTextField txtMateriaId;
    private javax.swing.JTextField txtMateriaNombre;
    // End of variables declaration//GEN-END:variables
}
