/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author carlo
 */
public class MPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MPrincipal
     */
    public MPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        mnuEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuMateria = new javax.swing.JMenu();
        mnuFormMateria = new javax.swing.JMenuItem();
        mnuAlumno = new javax.swing.JMenu();
        mnuFormAlumnos = new javax.swing.JMenuItem();
        mnuInscripciones = new javax.swing.JMenu();
        mnuFormInscripciones = new javax.swing.JMenuItem();
        mnuNotas = new javax.swing.JMenu();
        mnuFormNotas = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenu();
        mnuFormConsulta = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuEscritorio.setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout mnuEscritorioLayout = new javax.swing.GroupLayout(mnuEscritorio);
        mnuEscritorio.setLayout(mnuEscritorioLayout);
        mnuEscritorioLayout.setHorizontalGroup(
            mnuEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        mnuEscritorioLayout.setVerticalGroup(
            mnuEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuMateria.setText("Materias");

        mnuFormMateria.setText("Formulario de materias");
        mnuMateria.add(mnuFormMateria);

        jMenuBar1.add(mnuMateria);

        mnuAlumno.setText("Alumnos");

        mnuFormAlumnos.setText("Formulario de alumnos");
        mnuFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFormAlumnosActionPerformed(evt);
            }
        });
        mnuAlumno.add(mnuFormAlumnos);

        jMenuBar1.add(mnuAlumno);

        mnuInscripciones.setText("Inscripciones");

        mnuFormInscripciones.setText("Manejo de inscripciones");
        mnuInscripciones.add(mnuFormInscripciones);

        jMenuBar1.add(mnuInscripciones);

        mnuNotas.setText("Carga de notas");

        mnuFormNotas.setText("Manipulacion de notas");
        mnuNotas.add(mnuFormNotas);

        jMenuBar1.add(mnuNotas);

        mnuConsulta.setText("Consultas");

        mnuFormConsulta.setText("Consultar alumnos por materia");
        mnuConsulta.add(mnuFormConsulta);

        jMenuBar1.add(mnuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnuEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnuEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFormAlumnosActionPerformed
        // TODO add your handling code here:
        mnuEscritorio.removeAll();
        mnuEscritorio.repaint();
        FormAlumno formA = new FormAlumno();
        formA.setVisible(true);
        mnuEscritorio.add(formA);
        mnuEscritorio.moveToFront(formA);
    }//GEN-LAST:event_mnuFormAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAlumno;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuConsulta;
    private javax.swing.JDesktopPane mnuEscritorio;
    private javax.swing.JMenuItem mnuFormAlumnos;
    private javax.swing.JMenuItem mnuFormConsulta;
    private javax.swing.JMenuItem mnuFormInscripciones;
    private javax.swing.JMenuItem mnuFormMateria;
    private javax.swing.JMenuItem mnuFormNotas;
    private javax.swing.JMenu mnuInscripciones;
    private javax.swing.JMenu mnuMateria;
    private javax.swing.JMenu mnuNotas;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
